#!/usr/bin/with-contenv bash
# shellcheck shell=bash

# This is an install script that is designed to run after init-mods-package-install
# so it can take advantage of packages installed
# init-mods-end depends on this script so that later init and services wait until this script exits

echo "*** Removing existing par2cmdline packages ***"
#if [ -f /usr/local/bin/par2 ]; then
	apk del --purge -q par2cmdline
    echo "**** Installing par2cmdline-turbo ****"
	git clone https://github.com/animetosho/par2cmdline-turbo.git
	mkdir -p /tmp/par2
	cd /tmp/par2
	git clone https://github.com/animetosho/par2cmdline-turbo.git
	cd par2cmdline-turbo
	aclocal
	automake --add-missing
	autoconf
	./configure
	make
	make install
#    else
#        echo "**** par2cmdline-turbo already installed or platform unsupported ****"
#fi
