#!/usr/bin/with-contenv bash
# shellcheck shell=bash

# This is an install script that is designed to run after init-mods-package-install
# so it can take advantage of packages installed
# init-mods-end depends on this script so that later init and services wait until this script exits

echo "*** Removing existing par2cmdline packages ***"
if apk list --installed -q | grep par2cmdline &> /dev/null; then
    apk del --purge -q par2cmdline
fi

# if [[ -e "/usr/local/bin/par2" ]] && grep -q 'par2cmdline-turbo' <<< "$(/usr/local/bin/par2 -V)"; then
	git clone https://github.com/animetosho/par2cmdline-turbo.git
    if [[ -d "/par2cmdline-turbo/" ]]; then
        echo "**** Installing par2cmdline-turbo ****"
		mkdir -p /tmp/par2
		cd /tmp/par2
        git clone https://github.com/animetosho/par2cmdline-turbo.git
		cd par2cmdline-turbo
		aclocal
		automake --add-missing
		autoconf
		./configure
		make
		make install
    else
        echo "**** par2cmdline-turbo already installed or platform unsupported ****"
	fi
