#!/usr/bin/with-contenv bash
# shellcheck shell=bash

# This is the init file used for adding os or pip packages to install lists.
# It takes advantage of the built-in init-mods-package-install init script that comes with the baseimages.
# If using this, we need to make sure we set this init as a dependency of init-mods-package-install so this one runs first

if [ -f /sbin/apk ]; then
echo http://dl-cdn.alpinelinux.org/alpine/edge/main > /etc/apk/repositories
echo http://dl-cdn.alpinelinux.org/alpine/edge/community/ >> /etc/apk/repositories
apk --update upgrade
    echo "\
        bind-tools \
		libgomp	\
		tar \
		make \
		g++ \
		ca-certificates \
		wget \
		autoconf \
		automake \
		openmp \
		git \
		ffmpeg \
		p7zip" >> /mod-repo-packages-to-install.list
fi
