#!/usr/bin/with-contenv bash
# shellcheck shell=bash

# This is the init file used for adding os or pip packages to install lists.
# It takes advantage of the built-in init-mods-package-install init script that comes with the baseimages.
# If using this, we need to make sure we set this init as a dependency of init-mods-package-install so this one runs first

if [ -f /sbin/apk ]; then
echo http://dl-cdn.alpinelinux.org/alpine/edge/main > /etc/apk/repositories
echo http://dl-cdn.alpinelinux.org/alpine/edge/community/ >> /etc/apk/repositories
apk --update upgrade
echo "Phase 1 - Dependencies are being installed...."
apk add --no-cache --virtual=build-dependencies \
    --repository http://dl-cdn.alpinelinux.org/alpine/edge/main \
	tar \
	libgomp \
	make \
	g++ \
	ca-certificates \
	wget \
	autoconf \
	automake \
	openmp \
	git \
	build-base
update-ca-certificates
echo "Phase 1 - DONE"
echo " "
echo "Phase 2 - Binaries are being installed..."
apk add --no-cache \
    --repository http://dl-cdn.alpinelinux.org/alpine/edge/main \
	ffmpeg \
	openssl \
	p7zip \
	unzip \
	python3
echo "Phase 2 - DONE"
fi
