#!/usr/bin/with-contenv bash

## Ubuntu
if [ -f /usr/bin/apt ]; then
	echo "Distribution: Ubuntu/Debian"
	echo "LazyLibrarian Essentials - Installation Started"
	apt-get update
	apt-get install -y \
	wget \
	git \
	dialog \
	unzip \
	p7zip \
	ffmpeg \
	calibre
	echo "LazyLibrarian Essentials - Installation Ended"
fi
## Alpine
if [ -f /sbin/apk ]; then
	echo "Alpine Essentials are not implemented yet...Done"
fi
